### ISSUE TITLE
RuntimeError: The size of tensor a (74) must match the size of tensor b (8) at non-singleton dimension 1

### ISSUE THREAD

**Issue by tr-huyanh16** [amacati/SoulsAI#4]
hi i want to train Iudex, I composed up docker and ran python soulsai\distributed\client\main.py, but I encounter this problem:

PS E:\For the Dark Soul\SoulsAI> python soulsai\distributed\client\main.py
INFO:soulsai.distributed.client.dqn_client:Launching DQN client
INFO:soulsai.distributed.client.dqn_client:Press 'Enter' to end training
INFO:soulsai.distributed.client.connector:Waiting for model download...
INFO:soulsai.distributed.client.connector:Download complete, connector initialized
INFO:soulsai.distributed.client.dqn_client:Client node running
Traceback (most recent call last):
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\main.py", line 36, in <module>
    dqn_client(config)
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\dqn_client.py", line 52, in dqn_client
    _dqn_client(config)
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\dqn_client.py", line 109, in _dqn_client
    sample = con.transforms["obs"](sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thand\anaconda3\envs\soulsAI_env\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thand\anaconda3\envs\soulsAI_env\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\For the Dark Soul\SoulsAI\soulsai\core\transform.py", line 172, in forward
    x[sample_key][..., idx] = (x[sample_key][..., idx] - mean[..., idx]) / std[..., idx]
                               ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (74) must match the size of tensor b (8) at non-singleton dimension 1
[W520 16:19:36.000000000 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

I tried to change many values in config.yaml but nothing seems to work:

 # Environment information
env:
  name: SoulsGymIudex-v0
  vectorize: False
  kwargs:
    game_speed: 1.
  obs_shape: [74]
  n_actions: 20
  wrappers:
    IudexObservationWrapper:
      kwargs:

max_env_steps: null

# Algorithm choice
algorithm: DQN

# DQN parameters
dqn:
  batch_size: 64
  train_epochs: 25
  update_samples: 25
  fill_buffer: False
  min_samples: null
  max_model_delay: 10

  agent:
    type: DQNAgent
    kwargs:
      lr: 0.001
      gamma: 0.99
      multistep: 4
      grad_clip: 1.
      q_clip: 2
      device: cuda

  network:
    type: DQN
    kwargs:
      input_dims: 74
      output_dims: 20
      layer_dims: 128

  replay_buffer:
    type: ReplayBuffer
    kwargs:
      max_size: 100_000

  observation_transform:
    type: Normalize
    kwargs:
      keys:
        - obs
      shapes:
        - [8]

Can you look into this issue please? ty

**Comment by amacati** [comment]
Hi, your config seems off. The observation_transform seems off:

> observation_transform:
> type: Normalize
> kwargs:
> keys:
> - obs
> shapes:
> - [8]

Instead of having shapes [8], you should enter the real shape of your observation (74 in this case).

**Comment by tr-huyanh16** [comment]
I changed to 74 and it returns this error:

  observation_transform:
    type: Normalize
    kwargs:
      keys:
        - obs
      shapes:
        - [74] 

PS E:\For the Dark Soul\SoulsAI> python soulsai\distributed\client\main.py
INFO:soulsai.distributed.client.dqn_client:Launching DQN client
INFO:soulsai.distributed.client.dqn_client:Press 'Enter' to end training
INFO:soulsai.distributed.client.connector:Waiting for model download...
INFO:soulsai.distributed.client.connector:Download complete, connector initialized
INFO:soulsai.distributed.client.dqn_client:Client node running
Traceback (most recent call last):
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\main.py", line 36, in <module>
    dqn_client(config)
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\dqn_client.py", line 52, in dqn_client
    _dqn_client(config)
  File "E:\For the Dark Soul\SoulsAI\soulsai\distributed\client\dqn_client.py", line 111, in _dqn_client
    sample = con.transforms["action"](sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thand\anaconda3\envs\soulsAI_env\Lib\site-packages\torch\nn\modules\module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thand\anaconda3\envs\soulsAI_env\Lib\site-packages\torch\nn\modules\module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\For the Dark Soul\SoulsAI\soulsai\core\transform.py", line 411, in forward
    tf_idx = torch.multinomial(self.params["probs"], x[key].shape[0], replacement=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: invalid multinomial distribution (sum of probabilities <= 0)
[W520 18:29:31.000000000 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by amacati** [comment]
Is the config above the full config? What action transforms do you use?

**Comment by tr-huyanh16** [comment]
Here's my full config, im sorry because im new to RL so i may not fully understand your config.

```
# Create config.yaml file to overwrite default settings

# General settings
loglevel: info

# Redis settings
redis_address: localhost

local:

# Environment information
env:
  name: SoulsGymIudex-v0
  vectorize: False
  kwargs:
    game_speed: 1.
  obs_shape: [74]
  n_actions: 20
  wrappers:
    IudexObservationWrapper:
      kwargs:

max_env_steps: null

# Algorithm choice
algorithm: DQN

# DQN parameters
dqn:
  batch_size: 64
  train_epochs: 25
  update_samples: 25
  fill_buffer: False
  min_samples: null
  max_model_delay: 10

  agent:
    type: DQNAgent
    kwargs:
      lr: 0.001
      gamma: 0.99
      multistep: 4
      grad_clip: 1.
      q_clip: 2
      device: cuda

  network:
    type: DQN
    kwargs:
      input_dims: 74
      output_dims: 20
      layer_dims: 128

  replay_buffer:
    type: ReplayBuffer
    kwargs:
      max_size: 100_000

  observation_transform:
    type: Normalize
    kwargs:
      keys:
        - obs
      shapes:
        - [74]

  value_transform:
    type: Chain
    kwargs:
      transforms:
        - type: Mask
          kwargs:
            key: __value__
            mask_key: [info, action_mask]
        - type: GreedyAction
          kwargs:
            value_key: __value__
            action_key: action

  action_transform:
    type: Choice
    kwargs:
      key: action
      probs: [0.9, 0.1]
      transforms:
        - type: Identity
        - type: ReplaceWithNoise
          kwargs:
            key: action
            noise:
              type: MaskedDiscreteNoise
              kwargs:
                mask_key: [info, action_mask]
                size_n: 20

# Training node settings
checkpoint:
  save: False
  epochs: 100  # Checkpoint every 100th iteration
  save_buffer: False
  load: False
  load_buffer: False
  load_config: False

# Telemetry node settings
telemetry:
  update_interval: 5
  moving_average: 20
  transforms:
    - type: MetricByKey
      kwargs:
        key: ep_reward
        name: rewards
    - type: MetricByKey
      kwargs:
        key: ep_steps
        name: steps
    - type: MetricByKey
      kwargs:
        key: total_steps
        name: n_env_steps
    - type: CompareValue
      kwargs:
        key: ep_reward
        name: wins
        value: 200
        op: gt  # Greater than
    - type: Timer
  log_keys:
    - rewards_av
    - steps_av
  callbacks:
    - type: SaveBest
      kwargs:
        key: rewards_av
        channel: save_best

# Monitoring
monitoring:
  file_storage:
    path: /home/SoulsAI/saves
    plot:
      xkey: n_env_steps
      ykeys:
        - rewards_av
        - steps_av
        - wins_av
        - time
  grafana: True
  prometheus: True
  # wandb:
  #   project: soulsai_iudex
  #   entity: amacati
  #   group: state_obs
  #   save_dir: /home/SoulsAI/saves

# Client settings
max_episodes: -1  # -1 for infinite runs
enable_interrupt: True
step_delay: 0

watchdog:
  enable: False
  minimum_samples: -1
```
